### ISSUE TITLE
Add Pol.is Section to website

### ISSUE THREAD

**Issue by avenmia** [CodeforHawaii/website#42]
What is this project about? 

What are the project goals?

What project roles are involved?

What image can be associated with the project?

**Comment by rinanagashima** [comment]
What is this project about? 
The vHawaii project’s mission is to “reimagine a stronger, more efficient, and more connected democratic problem solving process for Hawai’i through the embrace of technology, out-of-the-box thinking, and a consensus-based approach to policy-making.” To fulfill this mission, we plan to create an online, consensus-based, community-driven policy problem solving model based on the successful vTaiwan model, which has been used to crowdsource critical policy solutions for Taiwan’s national government.

What are the project goals?  
This project, should it prove successful, will fill two persistent needs in Hawaii’s local governing landscape, which is making broad public participation easier for Hawaii residents, as well as enabling the crowdsourcing of creative, consensus-based, and actionable ideas from members of the public for public officials. We anticipate the success of this project will be achieved by centering our process around the open-source online conversation and opinion polling software Pol.is, which leverages AI opinion visualization to help identify divisions and provide diverse participants the knowledge to refine ideas towards the goal of reaching inter-group consensus. We envision this all-volunteer process will open up a new form of community-based leadership in our home state and can serve as a model for other communities.

What project roles are involved?
Project Coordinator, Research Lead, Outreach Lead, Website Designer

What image can be associated with the project?
![09f4c840292845a6a1c0ae5dd3770072(1)](https://user-images.githubusercontent.com/79285848/166405765-f5e64a2b-8ae7-4d3e-9f0e-ddc9c18ae920.png)
