### ISSUE TITLE
Add Hawaii Zoning Atlas section

### ISSUE THREAD

**Issue by avenmia** [CodeforHawaii/website#45]
What is this project about? (2 - 3 sentence summary)

What are the project goals?

What project roles are involved? (If someone were to join the project, what roles are needed)

What image can be associated with the project?

**Comment by kcoronel** [comment]
@avenmia here you go: 

What is this project about? 




What are the project goals?
The project's goals are to build an interactive online map to educate the public on zoning and land use issues and generate talking points for affordable housing advocates in Hawaii. Our second goal is to create a website that serves as a hub for the resulting coalition of researchers, educators, and advocates. 

What project roles are involved? 

We plan to have six teams of no less than four members each: one for each of Hawaii’s four counties with zoning powers, one technical team, and one policy team. The county teams will each be responsible for collecting and verifying regulatory data, identifying and reaching out to potential coalition members within their jurisdiction, and promoting the findings through local channels. The technical team will be responsible for building the project’s website and the interactive map. The policy team will be responsible for interpreting the regulatory data, drafting policy proposals  in partnership with coalition members, and circulating those proposals to researchers, reporters, and officials.


What image can be associated with the project?

**Comment by boobeh123** [comment]
Hello, I would help to help out and create the section for Hawaii Zoning Atlas. 
I have it completed in a forked version and will commit/push when given the green light. 

I have attached an image with my reply.
![HZA-one](https://user-images.githubusercontent.com/101483481/180344094-349c1ae9-c1e5-469b-98df-89e1d03d2140.png)
![HZA-two](https://user-images.githubusercontent.com/101483481/180344099-da46f40e-a44d-4a54-8c60-b8a131c215cf.png)
 What you will see in this image is not final and is subject to change.

**Comment by avenmia** [comment]
@boobeh123 This is looking great! Can you create a PR and assign me for review?

**Comment by boobeh123** [comment]
I'm glad to you think so, PR sent!

**Comment by avenmia** [comment]
@boobeh123 Code changes look good to me. How does the image look to you, @kcoronel?
